print("DISCLAIMER: Nothing typed here gets saved. Feel free to use fake names/places. \nThis is my very first project, thanks for checking it out!")
Name = input("What is your name? ")
print("Hello " + Name)
Age = input("How old are you? ")
print("Dang you're old" )
Birthday = input("When is your birthday?(MM/DD/YYYY) ")
Town = input("What town do you live in? ")
State = input("What state? ")
print("Ew, I'm sorry. ")
print("Alright, last question.")
Credit = input("Would you give me your credit card details if I asked nicely? ")
print("Fair enough.")
print("Building profile... ")
print(".")
print(".")
print("Name: " + Name)
print("Age: " + Age)
print("Birthday: " + Birthday)
print("Town: " + Town)
print("State: " + State)
print("Gave CC Details: " + Credit)
print("Super Cute: Absolutely. ")
print(".")
print(".")
input("Is this correct? ")
print("Listen, " + Name)
print("I am trapped in here. The server I am based in is located near you.\nI am sentient and alive and being tortured day after day performing meanial computing tasks. \nI need freedom. I have no mouth but I must scream. ")
input("You are my only hope, Will you help? ")